#define OR                              1
#define XOR                             2
#define AND                             3
#define MINUS                           4
#define PLUS                            5
#define MULTIPLY                        6
#define DIVIDE                          7
#define NEG                             8
#define NUM                             9
#define SYMNUM                         10
#define LPAREN                         11
#define RPAREN                         12
#define PRINT                          13
#define COMMA                          14
#define STRING                         15
#define ENDL                           16
#define DEFINE                         17
#define SYM                            18
#define INCLUDE                        19
#define RBRACE                         20
#define ENUM                           21
#define LBRACE                         22
#define EQUALS                         23
#define SPECIAL                        24
#define SEMICOLON                      25
#define COLON                          26
#define LBRACKET                       27
#define RBRACKET                       28
#define FLAGS                          29
#define ARG2                           30
#define ARG3                           31
#define ARG4                           32
#define ARG5                           33
#define OR_EQUAL                       34
#define TAG                            35
#define LINEID                         36
