#define OR                              1
#define XOR                             2
#define AND                             3
#define MINUS                           4
#define PLUS                            5
#define MULTIPLY                        6
#define DIVIDE                          7
#define NEG                             8
#define NUM                             9
#define SYMNUM                         10
#define LPAREN                         11
#define RPAREN                         12
#define NOP                            13
#define PRINT                          14
#define COMMA                          15
#define STRING                         16
#define ENDL                           17
#define DEFINE                         18
#define SYM                            19
#define INCLUDE                        20
#define RBRACE                         21
#define ENUM                           22
#define LBRACE                         23
#define EQUALS                         24
#define SPECIAL                        25
#define SEMICOLON                      26
#define COLON                          27
#define LBRACKET                       28
#define RBRACKET                       29
#define FLAGS                          30
#define ARG2                           31
#define ARG3                           32
#define ARG4                           33
#define ARG5                           34
#define OR_EQUAL                       35
#define TAG                            36
#define LINEID                         37
