MAKEWAD=../tools/makewad/makewad

ifneq ($(MAKECMDGOALS),clean)
include Makefile2
endif
ifeq ($(findstring msys,$(shell sh --version 2>nul)),msys)
export OSTYPE=msys
endif

wadmake: zdoom.lst $(MAKEWAD).exe
	$(MAKEWAD) -make wadmake zdoom.lst

clean:
ifeq ($(OSTYPE),msys)
	rm -f wadmake zdoom.pk3
else
	del /q /f wadmake zdoom.pk3 2>nul
endif

../tools/makewad/makewad.exe:
	$(MAKE) -C ../tools/makewad -f Makefile
