EXE = lemon.exe

CCDV = @../../ccdv
CC = gcc
CFLAGS = $(LOC) -D_WIN32 -Os -Wall -Wno-implicit -fomit-frame-pointer

OBJS = lemon.o

all: $(EXE)

.c.o:
	$(CCDV) $(CC) $(CFLAGS) -c -o $@ $<

$(EXE): $(OBJS)
	$(CCDV) $(CC) -o $(EXE) $(OBJS)

.PHONY: clean

clean:
	-del /q /f $(EXE) 2>nul
	-del /q /f *.o 2>nul

lemon.o: lemon.c lempar.c
