#define NOP                             1
#define OR                              2
#define XOR                             3
#define AND                             4
#define MINUS                           5
#define PLUS                            6
#define MULTIPLY                        7
#define DIVIDE                          8
#define NEG                             9
#define NUM                            10
#define SYMNUM                         11
#define LPAREN                         12
#define RPAREN                         13
#define DEFINE                         14
#define SYM                            15
#define RBRACE                         16
#define ENUM                           17
#define LBRACE                         18
#define COMMA                          19
#define EQUALS                         20
#define TAG                            21
#define LBRACKET                       22
#define RBRACKET                       23
#define FLAGS                          24
#define ARG2                           25
#define ARG3                           26
#define ARG4                           27
#define ARG5                           28
#define OR_EQUAL                       29
#define COLON                          30
