#define OR                              1
#define XOR                             2
#define AND                             3
#define MINUS                           4
#define PLUS                            5
#define MULTIPLY                        6
#define DIVIDE                          7
#define NEG                             8
#define EOI                             9
#define PRINT                          10
#define LPAREN                         11
#define RPAREN                         12
#define COMMA                          13
#define STRING                         14
#define ENDL                           15
#define NUM                            16
#define Actions                        17
#define LBRACE                         18
#define RBRACE                         19
#define SEMICOLON                      20
#define SYM                            21
#define OrgHeights                     22
#define ActionList                     23
#define RBARCE                         24
#define CodePConv                      25
#define OrgSprNames                    26
#define StateMap                       27
#define FirstState                     28
#define SpawnState                     29
#define DeathState                     30
#define SoundMap                       31
#define InfoNames                      32
#define ThingBits                      33
#define RenderStyles                   34
