#define OR                              1
#define XOR                             2
#define AND                             3
#define MINUS                           4
#define PLUS                            5
#define MULTIPLY                        6
#define DIVIDE                          7
#define NEG                             8
#define EOI                             9
#define PRINT                          10
#define LPAREN                         11
#define RPAREN                         12
#define COMMA                          13
#define STRING                         14
#define ENDL                           15
#define NUM                            16
#define Actions                        17
#define LBRACE                         18
#define RBRACE                         19
#define SEMICOLON                      20
#define SYM                            21
#define OrgHeights                     22
#define ActionList                     23
#define CodePConv                      24
#define OrgSprNames                    25
#define StateMap                       26
#define FirstState                     27
#define SpawnState                     28
#define DeathState                     29
#define SoundMap                       30
#define InfoNames                      31
#define ThingBits                      32
#define RenderStyles                   33
