#pragma once

enum
{
	Button_AM_PanLeft,
	Button_User2,	
	Button_Jump,	
	Button_Right,	
	Button_Zoom,	
	Button_Back,	
	Button_AM_ZoomIn,
	Button_Reload,	
	Button_LookDown,
	Button_AM_ZoomOut,
	Button_User4,	
	Button_Attack,	
	Button_User1,	
	Button_Klook,	
	Button_Forward,	
	Button_MoveDown,
	Button_AltAttack,
	Button_MoveLeft,
	Button_MoveRight,
	Button_AM_PanRight,
	Button_AM_PanUp,
	Button_Mlook,	
	Button_Crouch,	
	Button_Left,	
	Button_LookUp,	
	Button_User3,	
	Button_Strafe,	
	Button_AM_PanDown,
	Button_ShowScores,
	Button_Speed,	
	Button_Use,		
	Button_MoveUp,	
	NUM_ACTIONS
};

