// This file is included by d_dehacked.cpp twice.
// The first time is to prototype these functions, and the second
// time is to define them in the CodePtrs list. The macros are
// defined appropriately to get the desired effect each time.

ACTOR(MonsterRail)

WEAPON(FireRailgun)
WEAPON(FireRailgunLeft)
WEAPON(FireRailgunRight)
WEAPON(RailWait)
WEAPON(Light0)
WEAPON(WeaponReady)
WEAPON(Lower)
WEAPON(Raise)
WEAPON(Punch)
WEAPON(ReFire)
WEAPON(FirePistol)
WEAPON(Light1)
WEAPON(FireShotgun)
WEAPON(Light2)
WEAPON(FireShotgun2)
WEAPON(CheckReload)
WEAPON(OpenShotgun2)
WEAPON(LoadShotgun2)
WEAPON(CloseShotgun2)
WEAPON(FireCGun)
WEAPON(GunFlash)
WEAPON(FireMissile)
WEAPON(Saw)
WEAPON(FirePlasma)
WEAPON(BFGsound)
WEAPON(FireBFG)

ACTOR(BFGSpray)
#ifndef FROM_THINGDEF
// A_Explode needs to use A_ExplodeParams in DECORATE
ACTOR(Explode)
#endif
ACTOR(Pain)
ACTOR(PlayerScream)
ACTOR(NoBlocking)
ACTOR(XScream)
ACTOR(Look)
ACTOR(Chase)
ACTOR(FaceTarget)
ACTOR(PosAttack)
ACTOR(Scream)
ACTOR(SPosAttack)
ACTOR(VileChase)
ACTOR(VileStart)
ACTOR(VileTarget)
ACTOR(VileAttack)
ACTOR(StartFire)
ACTOR(Fire)
ACTOR(FireCrackle)
ACTOR(Tracer)
ACTOR(SkelWhoosh)
ACTOR(SkelFist)
ACTOR(SkelMissile)
ACTOR(FatRaise)
ACTOR(FatAttack1)
ACTOR(FatAttack2)
ACTOR(FatAttack3)
ACTOR(BossDeath)
ACTOR(CPosAttack)
ACTOR(CPosRefire)
ACTOR(TroopAttack)
ACTOR(SargAttack)
ACTOR(HeadAttack)
ACTOR(BruisAttack)
ACTOR(SkullAttack)
ACTOR(Metal)
ACTOR(SpidRefire)
ACTOR(BabyMetal)
ACTOR(BspiAttack)
ACTOR(Hoof)
ACTOR(CyberAttack)
ACTOR(PainAttack)
ACTOR(PainDie)
ACTOR(KeenDie)
ACTOR(BrainPain)
ACTOR(BrainScream)
ACTOR(BrainDie)
ACTOR(BrainAwake)
ACTOR(BrainSpit)
ACTOR(SpawnSound)
ACTOR(SpawnFly)
ACTOR(BrainExplode)
ACTOR(Die)
ACTOR(Detonate)
ACTOR(Mushroom)

ACTOR(SetFloorClip)
ACTOR(UnSetFloorClip)
ACTOR(HideThing)
ACTOR(UnHideThing)
ACTOR(SetInvulnerable)
ACTOR(UnSetInvulnerable)
ACTOR(SetReflective)
ACTOR(UnSetReflective)
ACTOR(SetReflectiveInvulnerable)
ACTOR(UnSetReflectiveInvulnerable)
ACTOR(SetShootable)
ACTOR(UnSetShootable)
ACTOR(NoGravity)
ACTOR(Gravity)
ACTOR(LowGravity)

#undef WEAPON
#undef ACTOR
