/* Generated by re2c 0.10.5 */
#line 1 "src/sc_man_scanner.re"
#define	YYCTYPE		char
#define	YYCURSOR	cursor
#define	YYLIMIT		limit
#define	YYMARKER	marker
#define YYFILL(n)	{}
#if 0	// As long as the buffer ends with '\n', we need do nothing special for YYFILL.
	// This buffer must be as large as the largest YYFILL call
	YYCTYPE eofbuf[9];
#define	YYFILL(n)	\
	{ if(!sc_End) { \
	   if(n == 2) { eofbuf[0] = *cursor; } \
	   else if(n >= 3 && n <= 9) { memcpy(eofbuf, cursor, n-1); } \
	   eofbuf[n-1] = '\n'; \
	   cursor = eofbuf; \
	   limit = eofbuf + n - 1; \
	   sc_End = true; } \
	} \
	assert(n <= sizeof eofbuf)	// Semicolon intentionally omitted
#endif

//#define YYDEBUG(s,c) { Printf ("%d: %02x\n", s, c); }
#define YYDEBUG(s,c)

	char *cursor = ScriptPtr;
	char *limit = ScriptEndPtr;

std1:
	tok = YYCURSOR;
std2:
#line 51 "src/sc_man_scanner.re"

	if (tokens)	// A well-defined scanner, based on the c.re example.
	{
#define RET(x)	sc_TokenType = x; goto normal_token;
	
#line 39 "src/sc_man_scanner.h"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if((YYLIMIT - YYCURSOR) < 18) YYFILL(18);
	yych = *YYCURSOR;
	switch(yych){
	case 0x09:
	case 0x0B:
	case 0x0C:
	case 0x0D:
	case ' ':	goto yy77;
	case 0x0A:	goto yy79;
	case '!':	goto yy53;
	case '"':	goto yy30;
	case '%':	goto yy43;
	case '&':	goto yy45;
	case '\'':	goto yy32;
	case '(':	goto yy65;
	case ')':	goto yy67;
	case '*':	goto yy41;
	case '+':	goto yy37;
	case ',':	goto yy61;
	case '-':	goto yy39;
	case '.':	goto yy28;
	case '/':	goto yy2;
	case '0':	goto yy25;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy27;
	case ':':	goto yy63;
	case ';':	goto yy55;
	case '<':	goto yy35;
	case '=':	goto yy51;
	case '>':	goto yy33;
	case '?':	goto yy75;
	case 'A':
	case 'a':	goto yy20;
	case 'B':
	case 'b':	goto yy4;
	case 'C':
	case 'c':	goto yy6;
	case 'D':
	case 'd':	goto yy7;
	case 'E':
	case 'e':	goto yy8;
	case 'F':
	case 'f':	goto yy9;
	case 'G':
	case 'g':	goto yy10;
	case 'H':
	case 'J':
	case 'K':
	case 'Q':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'h':
	case 'j':
	case 'k':
	case 'q':
	case 'x':
	case 'y':
	case 'z':	goto yy24;
	case 'I':
	case 'i':	goto yy11;
	case 'L':
	case 'l':	goto yy17;
	case 'M':
	case 'm':	goto yy18;
	case 'N':
	case 'n':	goto yy19;
	case 'O':
	case 'o':	goto yy22;
	case 'P':
	case 'p':	goto yy23;
	case 'R':
	case 'r':	goto yy12;
	case 'S':
	case 's':	goto yy13;
	case 'T':
	case 't':	goto yy21;
	case 'U':
	case 'u':	goto yy14;
	case 'V':
	case 'v':	goto yy15;
	case 'W':
	case 'w':	goto yy16;
	case '[':	goto yy69;
	case ']':	goto yy71;
	case '^':	goto yy47;
	case '{':	goto yy57;
	case '|':	goto yy49;
	case '}':	goto yy59;
	case '~':	goto yy73;
	default:	goto yy81;
	}
yy2:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '.') {
		if(yych == '*') goto yy577;
	} else {
		if(yych <= '/') goto yy575;
		if(yych == '=') goto yy573;
	}
yy3:
#line 200 "src/sc_man_scanner.re"
	{ RET('/'); }
#line 156 "src/sc_man_scanner.h"
yy4:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Y') {
		if(yych <= 'Q') {
			if(yych == 'O') goto yy560;
			goto yy176;
		} else {
			if(yych <= 'R') goto yy561;
			if(yych <= 'X') goto yy176;
			goto yy562;
		}
	} else {
		if(yych <= 'q') {
			if(yych == 'o') goto yy560;
			goto yy176;
		} else {
			if(yych <= 'r') goto yy561;
			if(yych == 'y') goto yy562;
			goto yy176;
		}
	}
yy5:
#line 146 "src/sc_man_scanner.re"
	{ RET(TK_Identifier); }
#line 181 "src/sc_man_scanner.h"
yy6:
	yych = *++YYCURSOR;
	switch(yych){
	case 'A':
	case 'a':	goto yy518;
	case 'H':
	case 'h':	goto yy519;
	case 'L':
	case 'l':	goto yy520;
	case 'O':
	case 'o':	goto yy521;
	case 'R':
	case 'r':	goto yy522;
	default:	goto yy176;
	}
yy7:
	yych = *++YYCURSOR;
	if(yych <= 'O') {
		if(yych == 'E') goto yy491;
		if(yych <= 'N') goto yy176;
		goto yy492;
	} else {
		if(yych <= 'e') {
			if(yych <= 'd') goto yy176;
			goto yy491;
		} else {
			if(yych == 'o') goto yy492;
			goto yy176;
		}
	}
yy8:
	yych = *++YYCURSOR;
	if(yych <= 'X') {
		if(yych <= 'N') {
			if(yych == 'L') goto yy456;
			if(yych <= 'M') goto yy176;
			goto yy457;
		} else {
			if(yych == 'V') goto yy458;
			if(yych <= 'W') goto yy176;
			goto yy459;
		}
	} else {
		if(yych <= 'n') {
			if(yych == 'l') goto yy456;
			if(yych <= 'm') goto yy176;
			goto yy457;
		} else {
			if(yych <= 'v') {
				if(yych <= 'u') goto yy176;
				goto yy458;
			} else {
				if(yych == 'x') goto yy459;
				goto yy176;
			}
		}
	}
yy9:
	yych = *++YYCURSOR;
	if(yych <= 'O') {
		if(yych <= 'I') {
			if(yych == 'A') goto yy433;
			if(yych <= 'H') goto yy176;
			goto yy434;
		} else {
			if(yych == 'L') goto yy435;
			if(yych <= 'N') goto yy176;
			goto yy436;
		}
	} else {
		if(yych <= 'i') {
			if(yych == 'a') goto yy433;
			if(yych <= 'h') goto yy176;
			goto yy434;
		} else {
			if(yych <= 'l') {
				if(yych <= 'k') goto yy176;
				goto yy435;
			} else {
				if(yych == 'o') goto yy436;
				goto yy176;
			}
		}
	}
yy10:
	yych = *++YYCURSOR;
	if(yych <= 'O') {
		if(yych == 'L') goto yy423;
		if(yych <= 'N') goto yy176;
		goto yy424;
	} else {
		if(yych <= 'l') {
			if(yych <= 'k') goto yy176;
			goto yy423;
		} else {
			if(yych == 'o') goto yy424;
			goto yy176;
		}
	}
yy11:
	yych = *++YYCURSOR;
	if(yych <= 'T') {
		if(yych <= 'G') {
			if(yych <= 'E') goto yy176;
			if(yych <= 'F') goto yy394;
			goto yy396;
		} else {
			if(yych == 'N') goto yy397;
			if(yych <= 'S') goto yy176;
			goto yy398;
		}
	} else {
		if(yych <= 'm') {
			if(yych <= 'e') goto yy176;
			if(yych <= 'f') goto yy394;
			if(yych <= 'g') goto yy396;
			goto yy176;
		} else {
			if(yych <= 'n') goto yy397;
			if(yych == 't') goto yy398;
			goto yy176;
		}
	}
yy12:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy386;
	if(yych == 'e') goto yy386;
	goto yy176;
yy13:
	yych = *++YYCURSOR;
	switch(yych){
	case 'B':
	case 'b':	goto yy326;
	case 'E':
	case 'e':	goto yy327;
	case 'H':
	case 'h':	goto yy328;
	case 'I':
	case 'i':	goto yy329;
	case 'O':
	case 'o':	goto yy330;
	case 'T':
	case 't':	goto yy331;
	case 'U':
	case 'u':	goto yy332;
	case 'W':
	case 'w':	goto yy333;
	default:	goto yy176;
	}
yy14:
	yych = *++YYCURSOR;
	switch(yych){
	case 'I':
	case 'i':	goto yy306;
	case 'L':
	case 'l':	goto yy307;
	case 'N':
	case 'n':	goto yy308;
	case 'S':
	case 's':	goto yy309;
	default:	goto yy176;
	}
yy15:
	yych = *++YYCURSOR;
	if(yych <= 'O') {
		if(yych == 'I') goto yy288;
		if(yych <= 'N') goto yy176;
		goto yy289;
	} else {
		if(yych <= 'i') {
			if(yych <= 'h') goto yy176;
			goto yy288;
		} else {
			if(yych == 'o') goto yy289;
			goto yy176;
		}
	}
yy16:
	yych = *++YYCURSOR;
	if(yych == 'H') goto yy283;
	if(yych == 'h') goto yy283;
	goto yy176;
yy17:
	yych = *++YYCURSOR;
	if(yych <= 'O') {
		if(yych == 'A') goto yy265;
		if(yych <= 'N') goto yy176;
		goto yy266;
	} else {
		if(yych <= 'a') {
			if(yych <= '`') goto yy176;
			goto yy265;
		} else {
			if(yych == 'o') goto yy266;
			goto yy176;
		}
	}
yy18:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy261;
	if(yych == 'o') goto yy261;
	goto yy176;
yy19:
	yych = *++YYCURSOR;
	if(yych <= 'O') {
		if(yych <= 'D') {
			if(yych == 'A') goto yy245;
			goto yy176;
		} else {
			if(yych <= 'E') goto yy246;
			if(yych <= 'N') goto yy176;
			goto yy247;
		}
	} else {
		if(yych <= 'd') {
			if(yych == 'a') goto yy245;
			goto yy176;
		} else {
			if(yych <= 'e') goto yy246;
			if(yych == 'o') goto yy247;
			goto yy176;
		}
	}
yy20:
	yych = *++YYCURSOR;
	if(yych <= 'U') {
		if(yych <= 'B') {
			if(yych <= 'A') goto yy176;
			goto yy227;
		} else {
			if(yych <= 'C') goto yy228;
			if(yych <= 'T') goto yy176;
			goto yy229;
		}
	} else {
		if(yych <= 'c') {
			if(yych <= 'a') goto yy176;
			if(yych <= 'b') goto yy227;
			goto yy228;
		} else {
			if(yych == 'u') goto yy229;
			goto yy176;
		}
	}
yy21:
	yych = *++YYCURSOR;
	if(yych <= 'R') {
		if(yych == 'H') goto yy209;
		if(yych <= 'Q') goto yy176;
		goto yy210;
	} else {
		if(yych <= 'h') {
			if(yych <= 'g') goto yy176;
			goto yy209;
		} else {
			if(yych == 'r') goto yy210;
			goto yy176;
		}
	}
yy22:
	yych = *++YYCURSOR;
	if(yych <= 'U') {
		if(yych == 'P') goto yy198;
		if(yych <= 'T') goto yy176;
		goto yy199;
	} else {
		if(yych <= 'p') {
			if(yych <= 'o') goto yy176;
			goto yy198;
		} else {
			if(yych == 'u') goto yy199;
			goto yy176;
		}
	}
yy23:
	yych = *++YYCURSOR;
	if(yych <= 'U') {
		if(yych == 'R') goto yy177;
		if(yych <= 'T') goto yy176;
		goto yy178;
	} else {
		if(yych <= 'r') {
			if(yych <= 'q') goto yy176;
			goto yy177;
		} else {
			if(yych == 'u') goto yy178;
			goto yy176;
		}
	}
yy24:
	yych = *++YYCURSOR;
	goto yy176;
yy25:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'X') goto yy172;
	if(yych == 'x') goto yy172;
	goto yy171;
yy26:
#line 149 "src/sc_man_scanner.re"
	{ RET(TK_IntConst); }
#line 483 "src/sc_man_scanner.h"
yy27:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy154;
yy28:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '.') goto yy141;
	if(yych <= '/') goto yy29;
	if(yych <= '9') goto yy142;
yy29:
#line 193 "src/sc_man_scanner.re"
	{ RET('.'); }
#line 497 "src/sc_man_scanner.h"
yy30:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych != 0x0A) goto yy132;
yy31:
#line 211 "src/sc_man_scanner.re"
	{
			SC_ScriptError ("Unexpected character: %c (ASCII %d)\n", *tok, *tok);
			goto std1;
		}
#line 508 "src/sc_man_scanner.h"
yy32:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 0x0A) goto yy31;
	goto yy127;
yy33:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '<') goto yy34;
	if(yych <= '=') goto yy116;
	if(yych <= '>') goto yy118;
yy34:
#line 203 "src/sc_man_scanner.re"
	{ RET('>'); }
#line 522 "src/sc_man_scanner.h"
yy35:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ';') goto yy36;
	if(yych <= '<') goto yy112;
	if(yych <= '=') goto yy110;
yy36:
#line 202 "src/sc_man_scanner.re"
	{ RET('<'); }
#line 531 "src/sc_man_scanner.h"
yy37:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '+') goto yy106;
	if(yych == '=') goto yy108;
#line 198 "src/sc_man_scanner.re"
	{ RET('+'); }
#line 538 "src/sc_man_scanner.h"
yy39:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '-') goto yy102;
	if(yych == '=') goto yy104;
#line 197 "src/sc_man_scanner.re"
	{ RET('-'); }
#line 545 "src/sc_man_scanner.h"
yy41:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '=') goto yy100;
#line 199 "src/sc_man_scanner.re"
	{ RET('*'); }
#line 551 "src/sc_man_scanner.h"
yy43:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '=') goto yy98;
#line 201 "src/sc_man_scanner.re"
	{ RET('%'); }
#line 557 "src/sc_man_scanner.h"
yy45:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '&') goto yy94;
	if(yych == '=') goto yy96;
#line 194 "src/sc_man_scanner.re"
	{ RET('&'); }
#line 564 "src/sc_man_scanner.h"
yy47:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '=') goto yy92;
#line 204 "src/sc_man_scanner.re"
	{ RET('^'); }
#line 570 "src/sc_man_scanner.h"
yy49:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '=') goto yy90;
	if(yych == '|') goto yy88;
#line 205 "src/sc_man_scanner.re"
	{ RET('|'); }
#line 577 "src/sc_man_scanner.h"
yy51:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '=') goto yy86;
#line 188 "src/sc_man_scanner.re"
	{ RET('='); }
#line 583 "src/sc_man_scanner.h"
yy53:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '=') goto yy84;
#line 195 "src/sc_man_scanner.re"
	{ RET('!'); }
#line 589 "src/sc_man_scanner.h"
yy55:
	++YYCURSOR;
#line 183 "src/sc_man_scanner.re"
	{ RET(';'); }
#line 594 "src/sc_man_scanner.h"
yy57:
	++YYCURSOR;
#line 184 "src/sc_man_scanner.re"
	{ RET('{'); }
#line 599 "src/sc_man_scanner.h"
yy59:
	++YYCURSOR;
#line 185 "src/sc_man_scanner.re"
	{ RET('}'); }
#line 604 "src/sc_man_scanner.h"
yy61:
	++YYCURSOR;
#line 186 "src/sc_man_scanner.re"
	{ RET(','); }
#line 609 "src/sc_man_scanner.h"
yy63:
	++YYCURSOR;
#line 187 "src/sc_man_scanner.re"
	{ RET(':'); }
#line 614 "src/sc_man_scanner.h"
yy65:
	++YYCURSOR;
#line 189 "src/sc_man_scanner.re"
	{ RET('('); }
#line 619 "src/sc_man_scanner.h"
yy67:
	++YYCURSOR;
#line 190 "src/sc_man_scanner.re"
	{ RET(')'); }
#line 624 "src/sc_man_scanner.h"
yy69:
	++YYCURSOR;
#line 191 "src/sc_man_scanner.re"
	{ RET('['); }
#line 629 "src/sc_man_scanner.h"
yy71:
	++YYCURSOR;
#line 192 "src/sc_man_scanner.re"
	{ RET(']'); }
#line 634 "src/sc_man_scanner.h"
yy73:
	++YYCURSOR;
#line 196 "src/sc_man_scanner.re"
	{ RET('~'); }
#line 639 "src/sc_man_scanner.h"
yy75:
	++YYCURSOR;
#line 206 "src/sc_man_scanner.re"
	{ RET('?'); }
#line 644 "src/sc_man_scanner.h"
yy77:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy83;
yy78:
#line 208 "src/sc_man_scanner.re"
	{ goto std1; }
#line 652 "src/sc_man_scanner.h"
yy79:
	++YYCURSOR;
#line 209 "src/sc_man_scanner.re"
	{ goto newline; }
#line 657 "src/sc_man_scanner.h"
yy81:
	yych = *++YYCURSOR;
	goto yy31;
yy82:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy83:
	if(yych <= 0x0A) {
		if(yych == 0x09) goto yy82;
		goto yy78;
	} else {
		if(yych <= 0x0D) goto yy82;
		if(yych == ' ') goto yy82;
		goto yy78;
	}
yy84:
	++YYCURSOR;
#line 182 "src/sc_man_scanner.re"
	{ RET(TK_Neq); }
#line 678 "src/sc_man_scanner.h"
yy86:
	++YYCURSOR;
#line 181 "src/sc_man_scanner.re"
	{ RET(TK_Eq); }
#line 683 "src/sc_man_scanner.h"
yy88:
	++YYCURSOR;
#line 178 "src/sc_man_scanner.re"
	{ RET(TK_OrOr); }
#line 688 "src/sc_man_scanner.h"
yy90:
	++YYCURSOR;
#line 171 "src/sc_man_scanner.re"
	{ RET(TK_OrEq); }
#line 693 "src/sc_man_scanner.h"
yy92:
	++YYCURSOR;
#line 170 "src/sc_man_scanner.re"
	{ RET(TK_XorEq); }
#line 698 "src/sc_man_scanner.h"
yy94:
	++YYCURSOR;
#line 177 "src/sc_man_scanner.re"
	{ RET(TK_AndAnd); }
#line 703 "src/sc_man_scanner.h"
yy96:
	++YYCURSOR;
#line 169 "src/sc_man_scanner.re"
	{ RET(TK_AndEq); }
#line 708 "src/sc_man_scanner.h"
yy98:
	++YYCURSOR;
#line 168 "src/sc_man_scanner.re"
	{ RET(TK_ModEq); }
#line 713 "src/sc_man_scanner.h"
yy100:
	++YYCURSOR;
#line 166 "src/sc_man_scanner.re"
	{ RET(TK_MulEq); }
#line 718 "src/sc_man_scanner.h"
yy102:
	++YYCURSOR;
#line 176 "src/sc_man_scanner.re"
	{ RET(TK_Decr); }
#line 723 "src/sc_man_scanner.h"
yy104:
	++YYCURSOR;
#line 165 "src/sc_man_scanner.re"
	{ RET(TK_SubEq); }
#line 728 "src/sc_man_scanner.h"
yy106:
	++YYCURSOR;
#line 175 "src/sc_man_scanner.re"
	{ RET(TK_Incr); }
#line 733 "src/sc_man_scanner.h"
yy108:
	++YYCURSOR;
#line 164 "src/sc_man_scanner.re"
	{ RET(TK_AddEq); }
#line 738 "src/sc_man_scanner.h"
yy110:
	++YYCURSOR;
#line 179 "src/sc_man_scanner.re"
	{ RET(TK_Leq); }
#line 743 "src/sc_man_scanner.h"
yy112:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '=') goto yy114;
#line 174 "src/sc_man_scanner.re"
	{ RET(TK_LShift); }
#line 749 "src/sc_man_scanner.h"
yy114:
	++YYCURSOR;
#line 163 "src/sc_man_scanner.re"
	{ RET(TK_LShiftEq); }
#line 754 "src/sc_man_scanner.h"
yy116:
	++YYCURSOR;
#line 180 "src/sc_man_scanner.re"
	{ RET(TK_Geq); }
#line 759 "src/sc_man_scanner.h"
yy118:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '<') goto yy119;
	if(yych <= '=') goto yy122;
	if(yych <= '>') goto yy120;
yy119:
#line 173 "src/sc_man_scanner.re"
	{ RET(TK_RShift); }
#line 768 "src/sc_man_scanner.h"
yy120:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '=') goto yy124;
#line 172 "src/sc_man_scanner.re"
	{ RET(TK_URShift); }
#line 774 "src/sc_man_scanner.h"
yy122:
	++YYCURSOR;
#line 162 "src/sc_man_scanner.re"
	{ RET(TK_RShiftEq); }
#line 779 "src/sc_man_scanner.h"
yy124:
	++YYCURSOR;
#line 161 "src/sc_man_scanner.re"
	{ RET(TK_URShiftEq); }
#line 784 "src/sc_man_scanner.h"
yy126:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy127:
	if(yych == 0x0A) goto yy128;
	if(yych == '\'') goto yy129;
	goto yy126;
yy128:
	YYCURSOR = YYMARKER;
	if(yyaccept <= 2) {
		if(yyaccept <= 1) {
			if(yyaccept <= 0) {
				goto yy3;
			} else {
				goto yy26;
			}
		} else {
			goto yy29;
		}
	} else {
		if(yyaccept <= 3) {
			goto yy31;
		} else {
			goto yy144;
		}
	}
yy129:
	++YYCURSOR;
#line 158 "src/sc_man_scanner.re"
	{ RET(TK_NameConst); }
#line 816 "src/sc_man_scanner.h"
yy131:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy132:
	if(yych <= '!') {
		if(yych == 0x0A) goto yy128;
		goto yy131;
	} else {
		if(yych <= '"') goto yy134;
		if(yych != '\\') goto yy131;
	}
yy133:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 'c') {
		if(yych <= '7') {
			if(yych <= '&') {
				if(yych == '"') goto yy131;
				goto yy128;
			} else {
				if(yych <= '\'') goto yy131;
				if(yych <= '/') goto yy128;
				goto yy137;
			}
		} else {
			if(yych <= '[') {
				if(yych == '?') goto yy131;
				goto yy128;
			} else {
				if(yych <= '\\') goto yy131;
				if(yych <= '`') goto yy128;
				goto yy131;
			}
		}
	} else {
		if(yych <= 'r') {
			if(yych <= 'm') {
				if(yych == 'f') goto yy131;
				goto yy128;
			} else {
				if(yych <= 'n') goto yy131;
				if(yych <= 'q') goto yy128;
				goto yy131;
			}
		} else {
			if(yych <= 'u') {
				if(yych == 't') goto yy131;
				goto yy128;
			} else {
				if(yych <= 'v') goto yy131;
				if(yych == 'x') goto yy136;
				goto yy128;
			}
		}
	}
yy134:
	++YYCURSOR;
#line 155 "src/sc_man_scanner.re"
	{ RET(TK_StringConst); }
#line 878 "src/sc_man_scanner.h"
yy136:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '@') {
		if(yych <= '/') goto yy128;
		if(yych <= '9') goto yy139;
		goto yy128;
	} else {
		if(yych <= 'F') goto yy139;
		if(yych <= '`') goto yy128;
		if(yych <= 'f') goto yy139;
		goto yy128;
	}
yy137:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '"') {
		if(yych == 0x0A) goto yy128;
		if(yych <= '!') goto yy131;
		goto yy134;
	} else {
		if(yych <= '7') {
			if(yych <= '/') goto yy131;
			goto yy137;
		} else {
			if(yych == '\\') goto yy133;
			goto yy131;
		}
	}
yy139:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '9') {
		if(yych <= '!') {
			if(yych == 0x0A) goto yy128;
			goto yy131;
		} else {
			if(yych <= '"') goto yy134;
			if(yych <= '/') goto yy131;
			goto yy139;
		}
	} else {
		if(yych <= '[') {
			if(yych <= '@') goto yy131;
			if(yych <= 'F') goto yy139;
			goto yy131;
		} else {
			if(yych <= '\\') goto yy133;
			if(yych <= '`') goto yy131;
			if(yych <= 'f') goto yy139;
			goto yy131;
		}
	}
yy141:
	yych = *++YYCURSOR;
	if(yych == '.') goto yy150;
	goto yy128;
yy142:
	yyaccept = 4;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	if(yych <= 'K') {
		if(yych <= 'D') {
			if(yych <= '/') goto yy144;
			if(yych <= '9') goto yy142;
		} else {
			if(yych <= 'E') goto yy145;
			if(yych <= 'F') goto yy146;
		}
	} else {
		if(yych <= 'e') {
			if(yych <= 'L') goto yy146;
			if(yych >= 'e') goto yy145;
		} else {
			if(yych <= 'f') goto yy146;
			if(yych == 'l') goto yy146;
		}
	}
yy144:
#line 152 "src/sc_man_scanner.re"
	{ RET(TK_FloatConst); }
#line 964 "src/sc_man_scanner.h"
yy145:
	yych = *++YYCURSOR;
	if(yych <= ',') {
		if(yych == '+') goto yy147;
		goto yy128;
	} else {
		if(yych <= '-') goto yy147;
		if(yych <= '/') goto yy128;
		if(yych <= '9') goto yy148;
		goto yy128;
	}
yy146:
	yych = *++YYCURSOR;
	goto yy144;
yy147:
	yych = *++YYCURSOR;
	if(yych <= '/') goto yy128;
	if(yych >= ':') goto yy128;
yy148:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 'K') {
		if(yych <= '9') {
			if(yych <= '/') goto yy144;
			goto yy148;
		} else {
			if(yych == 'F') goto yy146;
			goto yy144;
		}
	} else {
		if(yych <= 'f') {
			if(yych <= 'L') goto yy146;
			if(yych <= 'e') goto yy144;
			goto yy146;
		} else {
			if(yych == 'l') goto yy146;
			goto yy144;
		}
	}
yy150:
	++YYCURSOR;
#line 160 "src/sc_man_scanner.re"
	{ RET(TK_Ellipsis); }
#line 1009 "src/sc_man_scanner.h"
yy152:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'E') goto yy162;
	if(yych == 'e') goto yy162;
	goto yy161;
yy153:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
yy154:
	if(yych <= 'L') {
		if(yych <= '9') {
			if(yych == '.') goto yy152;
			if(yych <= '/') goto yy26;
			goto yy153;
		} else {
			if(yych == 'E') goto yy155;
			if(yych <= 'K') goto yy26;
			goto yy156;
		}
	} else {
		if(yych <= 'e') {
			if(yych == 'U') goto yy156;
			if(yych <= 'd') goto yy26;
		} else {
			if(yych <= 'l') {
				if(yych <= 'k') goto yy26;
				goto yy156;
			} else {
				if(yych == 'u') goto yy156;
				goto yy26;
			}
		}
	}
yy155:
	yych = *++YYCURSOR;
	if(yych <= ',') {
		if(yych == '+') goto yy157;
		goto yy128;
	} else {
		if(yych <= '-') goto yy157;
		if(yych <= '/') goto yy128;
		if(yych <= '9') goto yy158;
		goto yy128;
	}
yy156:
	yych = *++YYCURSOR;
	goto yy26;
yy157:
	yych = *++YYCURSOR;
	if(yych <= '/') goto yy128;
	if(yych >= ':') goto yy128;
yy158:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 'K') {
		if(yych <= '9') {
			if(yych <= '/') goto yy144;
			goto yy158;
		} else {
			if(yych == 'F') goto yy146;
			goto yy144;
		}
	} else {
		if(yych <= 'f') {
			if(yych <= 'L') goto yy146;
			if(yych <= 'e') goto yy144;
			goto yy146;
		} else {
			if(yych == 'l') goto yy146;
			goto yy144;
		}
	}
yy160:
	yyaccept = 4;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
yy161:
	if(yych <= 'K') {
		if(yych <= 'D') {
			if(yych <= '/') goto yy144;
			if(yych <= '9') goto yy160;
			goto yy144;
		} else {
			if(yych <= 'E') goto yy166;
			if(yych <= 'F') goto yy146;
			goto yy144;
		}
	} else {
		if(yych <= 'e') {
			if(yych <= 'L') goto yy146;
			if(yych <= 'd') goto yy144;
			goto yy166;
		} else {
			if(yych <= 'f') goto yy146;
			if(yych == 'l') goto yy146;
			goto yy144;
		}
	}
yy162:
	yych = *++YYCURSOR;
	if(yych <= ',') {
		if(yych != '+') goto yy128;
	} else {
		if(yych <= '-') goto yy163;
		if(yych <= '/') goto yy128;
		if(yych <= '9') goto yy164;
		goto yy128;
	}
yy163:
	yych = *++YYCURSOR;
	if(yych <= '/') goto yy128;
	if(yych >= ':') goto yy128;
yy164:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 'K') {
		if(yych <= '9') {
			if(yych <= '/') goto yy144;
			goto yy164;
		} else {
			if(yych == 'F') goto yy146;
			goto yy144;
		}
	} else {
		if(yych <= 'f') {
			if(yych <= 'L') goto yy146;
			if(yych <= 'e') goto yy144;
			goto yy146;
		} else {
			if(yych == 'l') goto yy146;
			goto yy144;
		}
	}
yy166:
	yych = *++YYCURSOR;
	if(yych <= ',') {
		if(yych != '+') goto yy128;
	} else {
		if(yych <= '-') goto yy167;
		if(yych <= '/') goto yy128;
		if(yych <= '9') goto yy168;
		goto yy128;
	}
yy167:
	yych = *++YYCURSOR;
	if(yych <= '/') goto yy128;
	if(yych >= ':') goto yy128;
yy168:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 'K') {
		if(yych <= '9') {
			if(yych <= '/') goto yy144;
			goto yy168;
		} else {
			if(yych == 'F') goto yy146;
			goto yy144;
		}
	} else {
		if(yych <= 'f') {
			if(yych <= 'L') goto yy146;
			if(yych <= 'e') goto yy144;
			goto yy146;
		} else {
			if(yych == 'l') goto yy146;
			goto yy144;
		}
	}
yy170:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
yy171:
	if(yych <= 'L') {
		if(yych <= '9') {
			if(yych == '.') goto yy152;
			if(yych <= '/') goto yy26;
			goto yy170;
		} else {
			if(yych == 'E') goto yy155;
			if(yych <= 'K') goto yy26;
			goto yy156;
		}
	} else {
		if(yych <= 'e') {
			if(yych == 'U') goto yy156;
			if(yych <= 'd') goto yy26;
			goto yy155;
		} else {
			if(yych <= 'l') {
				if(yych <= 'k') goto yy26;
				goto yy156;
			} else {
				if(yych == 'u') goto yy156;
				goto yy26;
			}
		}
	}
yy172:
	yych = *++YYCURSOR;
	if(yych <= '@') {
		if(yych <= '/') goto yy128;
		if(yych >= ':') goto yy128;
	} else {
		if(yych <= 'F') goto yy173;
		if(yych <= '`') goto yy128;
		if(yych >= 'g') goto yy128;
	}
yy173:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 'T') {
		if(yych <= '@') {
			if(yych <= '/') goto yy26;
			if(yych <= '9') goto yy173;
			goto yy26;
		} else {
			if(yych <= 'F') goto yy173;
			if(yych == 'L') goto yy156;
			goto yy26;
		}
	} else {
		if(yych <= 'k') {
			if(yych <= 'U') goto yy156;
			if(yych <= '`') goto yy26;
			if(yych <= 'f') goto yy173;
			goto yy26;
		} else {
			if(yych <= 'l') goto yy156;
			if(yych == 'u') goto yy156;
			goto yy26;
		}
	}
yy175:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy176:
	if(yych <= 'Z') {
		if(yych <= '/') goto yy5;
		if(yych <= '9') goto yy175;
		if(yych <= '@') goto yy5;
		goto yy175;
	} else {
		if(yych <= '_') {
			if(yych <= '^') goto yy5;
			goto yy175;
		} else {
			if(yych <= '`') goto yy5;
			if(yych <= 'z') goto yy175;
			goto yy5;
		}
	}
yy177:
	yych = *++YYCURSOR;
	if(yych <= 'O') {
		if(yych == 'I') goto yy185;
		if(yych <= 'N') goto yy176;
		goto yy184;
	} else {
		if(yych <= 'i') {
			if(yych <= 'h') goto yy176;
			goto yy185;
		} else {
			if(yych == 'o') goto yy184;
			goto yy176;
		}
	}
yy178:
	yych = *++YYCURSOR;
	if(yych == 'B') goto yy179;
	if(yych != 'b') goto yy176;
yy179:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy180;
	if(yych != 'l') goto yy176;
yy180:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy181;
	if(yych != 'i') goto yy176;
yy181:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy182;
	if(yych != 'c') goto yy176;
yy182:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy183;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy183;
			if(yych <= 'z') goto yy175;
		}
	}
yy183:
#line 121 "src/sc_man_scanner.re"
	{ RET(TK_Public); }
#line 1320 "src/sc_man_scanner.h"
yy184:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy191;
	if(yych == 't') goto yy191;
	goto yy176;
yy185:
	yych = *++YYCURSOR;
	if(yych == 'V') goto yy186;
	if(yych != 'v') goto yy176;
yy186:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy187;
	if(yych != 'a') goto yy176;
yy187:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy188;
	if(yych != 't') goto yy176;
yy188:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy189;
	if(yych != 'e') goto yy176;
yy189:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy190;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy190;
			if(yych <= 'z') goto yy175;
		}
	}
yy190:
#line 123 "src/sc_man_scanner.re"
	{ RET(TK_Private); }
#line 1359 "src/sc_man_scanner.h"
yy191:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy192;
	if(yych != 'e') goto yy176;
yy192:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy193;
	if(yych != 'c') goto yy176;
yy193:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy194;
	if(yych != 't') goto yy176;
yy194:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy195;
	if(yych != 'e') goto yy176;
yy195:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy196;
	if(yych != 'd') goto yy176;
yy196:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy197;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy197;
			if(yych <= 'z') goto yy175;
		}
	}
yy197:
#line 122 "src/sc_man_scanner.re"
	{ RET(TK_Protected); }
#line 1397 "src/sc_man_scanner.h"
yy198:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy202;
	if(yych == 't') goto yy202;
	goto yy176;
yy199:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy200;
	if(yych != 't') goto yy176;
yy200:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy201;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy201;
			if(yych <= 'z') goto yy175;
		}
	}
yy201:
#line 113 "src/sc_man_scanner.re"
	{ RET(TK_Out); }
#line 1424 "src/sc_man_scanner.h"
yy202:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy203;
	if(yych != 'i') goto yy176;
yy203:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy204;
	if(yych != 'o') goto yy176;
yy204:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy205;
	if(yych != 'n') goto yy176;
yy205:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy206;
	if(yych != 'a') goto yy176;
yy206:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy207;
	if(yych != 'l') goto yy176;
yy207:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy208;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy208;
			if(yych <= 'z') goto yy175;
		}
	}
yy208:
#line 133 "src/sc_man_scanner.re"
	{ RET(TK_Optional); }
#line 1462 "src/sc_man_scanner.h"
yy209:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy222;
	if(yych == 'r') goto yy222;
	goto yy176;
yy210:
	yych = *++YYCURSOR;
	if(yych <= 'U') {
		if(yych == 'A') goto yy212;
		if(yych <= 'T') goto yy176;
	} else {
		if(yych <= 'a') {
			if(yych <= '`') goto yy176;
			goto yy212;
		} else {
			if(yych != 'u') goto yy176;
		}
	}
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy220;
	if(yych == 'e') goto yy220;
	goto yy176;
yy212:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy213;
	if(yych != 'n') goto yy176;
yy213:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy214;
	if(yych != 's') goto yy176;
yy214:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy215;
	if(yych != 'i') goto yy176;
yy215:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy216;
	if(yych != 'e') goto yy176;
yy216:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy217;
	if(yych != 'n') goto yy176;
yy217:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy218;
	if(yych != 't') goto yy176;
yy218:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy219;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy219;
			if(yych <= 'z') goto yy175;
		}
	}
yy219:
#line 117 "src/sc_man_scanner.re"
	{ RET(TK_Transient); }
#line 1526 "src/sc_man_scanner.h"
yy220:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy221;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy221;
			if(yych <= 'z') goto yy175;
		}
	}
yy221:
#line 104 "src/sc_man_scanner.re"
	{ RET(TK_True); }
#line 1544 "src/sc_man_scanner.h"
yy222:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy223;
	if(yych != 'o') goto yy176;
yy223:
	yych = *++YYCURSOR;
	if(yych == 'W') goto yy224;
	if(yych != 'w') goto yy176;
yy224:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy225;
	if(yych != 's') goto yy176;
yy225:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy226;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy226;
			if(yych <= 'z') goto yy175;
		}
	}
yy226:
#line 119 "src/sc_man_scanner.re"
	{ RET(TK_Throws); }
#line 1574 "src/sc_man_scanner.h"
yy227:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy238;
	if(yych == 's') goto yy238;
	goto yy176;
yy228:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy233;
	if(yych == 't') goto yy233;
	goto yy176;
yy229:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy230;
	if(yych != 't') goto yy176;
yy230:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy231;
	if(yych != 'o') goto yy176;
yy231:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy232;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy232;
			if(yych <= 'z') goto yy175;
		}
	}
yy232:
#line 109 "src/sc_man_scanner.re"
	{ RET(TK_Auto); }
#line 1610 "src/sc_man_scanner.h"
yy233:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy234;
	if(yych != 'i') goto yy176;
yy234:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy235;
	if(yych != 'o') goto yy176;
yy235:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy236;
	if(yych != 'n') goto yy176;
yy236:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy237;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy237;
			if(yych <= 'z') goto yy175;
		}
	}
yy237:
#line 144 "src/sc_man_scanner.re"
	{ RET(TK_Action); }
#line 1640 "src/sc_man_scanner.h"
yy238:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy239;
	if(yych != 't') goto yy176;
yy239:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy240;
	if(yych != 'r') goto yy176;
yy240:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy241;
	if(yych != 'a') goto yy176;
yy241:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy242;
	if(yych != 'c') goto yy176;
yy242:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy243;
	if(yych != 't') goto yy176;
yy243:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy244;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy244;
			if(yych <= 'z') goto yy175;
		}
	}
yy244:
#line 102 "src/sc_man_scanner.re"
	{ RET(TK_Abstract); }
#line 1678 "src/sc_man_scanner.h"
yy245:
	yych = *++YYCURSOR;
	if(yych <= 'T') {
		if(yych == 'M') goto yy253;
		if(yych <= 'S') goto yy176;
		goto yy254;
	} else {
		if(yych <= 'm') {
			if(yych <= 'l') goto yy176;
			goto yy253;
		} else {
			if(yych == 't') goto yy254;
			goto yy176;
		}
	}
yy246:
	yych = *++YYCURSOR;
	if(yych == 'W') goto yy251;
	if(yych == 'w') goto yy251;
	goto yy176;
yy247:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy248;
	if(yych != 'n') goto yy176;
yy248:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy249;
	if(yych != 'e') goto yy176;
yy249:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy250;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy250;
			if(yych <= 'z') goto yy175;
		}
	}
yy250:
#line 106 "src/sc_man_scanner.re"
	{ RET(TK_None); }
#line 1724 "src/sc_man_scanner.h"
yy251:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy252;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy252;
			if(yych <= 'z') goto yy175;
		}
	}
yy252:
#line 107 "src/sc_man_scanner.re"
	{ RET(TK_New); }
#line 1742 "src/sc_man_scanner.h"
yy253:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy259;
	if(yych == 'e') goto yy259;
	goto yy176;
yy254:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy255;
	if(yych != 'i') goto yy176;
yy255:
	yych = *++YYCURSOR;
	if(yych == 'V') goto yy256;
	if(yych != 'v') goto yy176;
yy256:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy257;
	if(yych != 'e') goto yy176;
yy257:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy258;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy258;
			if(yych <= 'z') goto yy175;
		}
	}
yy258:
#line 112 "src/sc_man_scanner.re"
	{ RET(TK_Native); }
#line 1777 "src/sc_man_scanner.h"
yy259:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy260;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy260;
			if(yych <= 'z') goto yy175;
		}
	}
yy260:
#line 95 "src/sc_man_scanner.re"
	{ RET(TK_Name); }
#line 1795 "src/sc_man_scanner.h"
yy261:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy262;
	if(yych != 'd') goto yy176;
yy262:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy263;
	if(yych != 'e') goto yy176;
yy263:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy264;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy264;
			if(yych <= 'z') goto yy175;
		}
	}
yy264:
#line 93 "src/sc_man_scanner.re"
	{ RET(TK_Mode); }
#line 1821 "src/sc_man_scanner.h"
yy265:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy278;
	if(yych == 't') goto yy278;
	goto yy176;
yy266:
	yych = *++YYCURSOR;
	if(yych <= 'N') {
		if(yych == 'C') goto yy268;
		if(yych <= 'M') goto yy176;
	} else {
		if(yych <= 'c') {
			if(yych <= 'b') goto yy176;
			goto yy268;
		} else {
			if(yych != 'n') goto yy176;
		}
	}
	yych = *++YYCURSOR;
	if(yych == 'G') goto yy276;
	if(yych == 'g') goto yy276;
	goto yy176;
yy268:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy269;
	if(yych != 'a') goto yy176;
yy269:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy270;
	if(yych != 'l') goto yy176;
yy270:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy271;
	if(yych != 'i') goto yy176;
yy271:
	yych = *++YYCURSOR;
	if(yych == 'Z') goto yy272;
	if(yych != 'z') goto yy176;
yy272:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy273;
	if(yych != 'e') goto yy176;
yy273:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy274;
	if(yych != 'd') goto yy176;
yy274:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy275;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy275;
			if(yych <= 'z') goto yy175;
		}
	}
yy275:
#line 127 "src/sc_man_scanner.re"
	{ RET(TK_Localized); }
#line 1885 "src/sc_man_scanner.h"
yy276:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy277;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy277;
			if(yych <= 'z') goto yy175;
		}
	}
yy277:
#line 88 "src/sc_man_scanner.re"
	{ RET(TK_Long); }
#line 1903 "src/sc_man_scanner.h"
yy278:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy279;
	if(yych != 'e') goto yy176;
yy279:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy280;
	if(yych != 'n') goto yy176;
yy280:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy281;
	if(yych != 't') goto yy176;
yy281:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy282;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy282;
			if(yych <= 'z') goto yy175;
		}
	}
yy282:
#line 128 "src/sc_man_scanner.re"
	{ RET(TK_Latent); }
#line 1933 "src/sc_man_scanner.h"
yy283:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy284;
	if(yych != 'i') goto yy176;
yy284:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy285;
	if(yych != 'l') goto yy176;
yy285:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy286;
	if(yych != 'e') goto yy176;
yy286:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy287;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy287;
			if(yych <= 'z') goto yy175;
		}
	}
yy287:
#line 75 "src/sc_man_scanner.re"
	{ RET(TK_While); }
#line 1963 "src/sc_man_scanner.h"
yy288:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy300;
	if(yych == 'r') goto yy300;
	goto yy176;
yy289:
	yych = *++YYCURSOR;
	if(yych <= 'L') {
		if(yych == 'I') goto yy291;
		if(yych <= 'K') goto yy176;
	} else {
		if(yych <= 'i') {
			if(yych <= 'h') goto yy176;
			goto yy291;
		} else {
			if(yych != 'l') goto yy176;
		}
	}
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy294;
	if(yych == 'a') goto yy294;
	goto yy176;
yy291:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy292;
	if(yych != 'd') goto yy176;
yy292:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy293;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy293;
			if(yych <= 'z') goto yy175;
		}
	}
yy293:
#line 90 "src/sc_man_scanner.re"
	{ RET(TK_Void); }
#line 2007 "src/sc_man_scanner.h"
yy294:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy295;
	if(yych != 't') goto yy176;
yy295:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy296;
	if(yych != 'i') goto yy176;
yy296:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy297;
	if(yych != 'l') goto yy176;
yy297:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy298;
	if(yych != 'e') goto yy176;
yy298:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy299;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy299;
			if(yych <= 'z') goto yy175;
		}
	}
yy299:
#line 74 "src/sc_man_scanner.re"
	{ RET(TK_Volatile); }
#line 2041 "src/sc_man_scanner.h"
yy300:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy301;
	if(yych != 't') goto yy176;
yy301:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy302;
	if(yych != 'u') goto yy176;
yy302:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy303;
	if(yych != 'a') goto yy176;
yy303:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy304;
	if(yych != 'l') goto yy176;
yy304:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy305;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy305;
			if(yych <= 'z') goto yy175;
		}
	}
yy305:
#line 135 "src/sc_man_scanner.re"
	{ RET(TK_Virtual); }
#line 2075 "src/sc_man_scanner.h"
yy306:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy323;
	if(yych == 'n') goto yy323;
	goto yy176;
yy307:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy319;
	if(yych == 'o') goto yy319;
	goto yy176;
yy308:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy315;
	if(yych == 't') goto yy315;
	goto yy176;
yy309:
	yych = *++YYCURSOR;
	if(yych == 'H') goto yy310;
	if(yych != 'h') goto yy176;
yy310:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy311;
	if(yych != 'o') goto yy176;
yy311:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy312;
	if(yych != 'r') goto yy176;
yy312:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy313;
	if(yych != 't') goto yy176;
yy313:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy314;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy314;
			if(yych <= 'z') goto yy175;
		}
	}
yy314:
#line 85 "src/sc_man_scanner.re"
	{ RET(TK_UShort); }
#line 2124 "src/sc_man_scanner.h"
yy315:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy316;
	if(yych != 'i') goto yy176;
yy316:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy317;
	if(yych != 'l') goto yy176;
yy317:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy318;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy318;
			if(yych <= 'z') goto yy175;
		}
	}
yy318:
#line 73 "src/sc_man_scanner.re"
	{ RET(TK_Until); }
#line 2150 "src/sc_man_scanner.h"
yy319:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy320;
	if(yych != 'n') goto yy176;
yy320:
	yych = *++YYCURSOR;
	if(yych == 'G') goto yy321;
	if(yych != 'g') goto yy176;
yy321:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy322;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy322;
			if(yych <= 'z') goto yy175;
		}
	}
yy322:
#line 89 "src/sc_man_scanner.re"
	{ RET(TK_ULong); }
#line 2176 "src/sc_man_scanner.h"
yy323:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy324;
	if(yych != 't') goto yy176;
yy324:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy325;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy325;
			if(yych <= 'z') goto yy175;
		}
	}
yy325:
#line 87 "src/sc_man_scanner.re"
	{ RET(TK_UInt); }
#line 2198 "src/sc_man_scanner.h"
yy326:
	yych = *++YYCURSOR;
	if(yych == 'Y') goto yy382;
	if(yych == 'y') goto yy382;
	goto yy176;
yy327:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy379;
	if(yych == 'l') goto yy379;
	goto yy176;
yy328:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy375;
	if(yych == 'o') goto yy375;
	goto yy176;
yy329:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy368;
	if(yych == 'n') goto yy368;
	goto yy176;
yy330:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy364;
	if(yych == 'u') goto yy364;
	goto yy176;
yy331:
	yych = *++YYCURSOR;
	if(yych <= 'R') {
		if(yych <= 'N') {
			if(yych == 'A') goto yy343;
			goto yy176;
		} else {
			if(yych <= 'O') goto yy345;
			if(yych <= 'Q') goto yy176;
			goto yy344;
		}
	} else {
		if(yych <= 'n') {
			if(yych == 'a') goto yy343;
			goto yy176;
		} else {
			if(yych <= 'o') goto yy345;
			if(yych == 'r') goto yy344;
			goto yy176;
		}
	}
yy332:
	yych = *++YYCURSOR;
	if(yych == 'P') goto yy339;
	if(yych == 'p') goto yy339;
	goto yy176;
yy333:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy334;
	if(yych != 'i') goto yy176;
yy334:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy335;
	if(yych != 't') goto yy176;
yy335:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy336;
	if(yych != 'c') goto yy176;
yy336:
	yych = *++YYCURSOR;
	if(yych == 'H') goto yy337;
	if(yych != 'h') goto yy176;
yy337:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy338;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy338;
			if(yych <= 'z') goto yy175;
		}
	}
yy338:
#line 72 "src/sc_man_scanner.re"
	{ RET(TK_Switch); }
#line 2283 "src/sc_man_scanner.h"
yy339:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy340;
	if(yych != 'e') goto yy176;
yy340:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy341;
	if(yych != 'r') goto yy176;
yy341:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy342;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy342;
			if(yych <= 'z') goto yy175;
		}
	}
yy342:
#line 136 "src/sc_man_scanner.re"
	{ RET(TK_Super); }
#line 2309 "src/sc_man_scanner.h"
yy343:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy356;
	if(yych == 't') goto yy356;
	goto yy176;
yy344:
	yych = *++YYCURSOR;
	if(yych <= 'U') {
		if(yych == 'I') goto yy348;
		if(yych <= 'T') goto yy176;
		goto yy349;
	} else {
		if(yych <= 'i') {
			if(yych <= 'h') goto yy176;
			goto yy348;
		} else {
			if(yych == 'u') goto yy349;
			goto yy176;
		}
	}
yy345:
	yych = *++YYCURSOR;
	if(yych == 'P') goto yy346;
	if(yych != 'p') goto yy176;
yy346:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy347;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy347;
			if(yych <= 'z') goto yy175;
		}
	}
yy347:
#line 139 "src/sc_man_scanner.re"
	{ RET(TK_Stop); }
#line 2351 "src/sc_man_scanner.h"
yy348:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy353;
	if(yych == 'n') goto yy353;
	goto yy176;
yy349:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy350;
	if(yych != 'c') goto yy176;
yy350:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy351;
	if(yych != 't') goto yy176;
yy351:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy352;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy352;
			if(yych <= 'z') goto yy175;
		}
	}
yy352:
#line 91 "src/sc_man_scanner.re"
	{ RET(TK_Struct); }
#line 2382 "src/sc_man_scanner.h"
yy353:
	yych = *++YYCURSOR;
	if(yych == 'G') goto yy354;
	if(yych != 'g') goto yy176;
yy354:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy355;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy355;
			if(yych <= 'z') goto yy175;
		}
	}
yy355:
#line 96 "src/sc_man_scanner.re"
	{ RET(TK_String); }
#line 2404 "src/sc_man_scanner.h"
yy356:
	yych = *++YYCURSOR;
	if(yych <= 'I') {
		if(yych == 'E') goto yy357;
		if(yych <= 'H') goto yy176;
		goto yy359;
	} else {
		if(yych <= 'e') {
			if(yych <= 'd') goto yy176;
		} else {
			if(yych == 'i') goto yy359;
			goto yy176;
		}
	}
yy357:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '@') {
			if(yych <= '/') goto yy358;
			if(yych <= '9') goto yy175;
		} else {
			if(yych == 'S') goto yy362;
			goto yy175;
		}
	} else {
		if(yych <= '`') {
			if(yych == '_') goto yy175;
		} else {
			if(yych == 's') goto yy362;
			if(yych <= 'z') goto yy175;
		}
	}
yy358:
#line 98 "src/sc_man_scanner.re"
	{ RET(TK_State); }
#line 2440 "src/sc_man_scanner.h"
yy359:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy360;
	if(yych != 'c') goto yy176;
yy360:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy361;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy361;
			if(yych <= 'z') goto yy175;
		}
	}
yy361:
#line 116 "src/sc_man_scanner.re"
	{ RET(TK_Static); }
#line 2462 "src/sc_man_scanner.h"
yy362:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy363;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy363;
			if(yych <= 'z') goto yy175;
		}
	}
yy363:
#line 71 "src/sc_man_scanner.re"
	{ RET(TK_States); }
#line 2480 "src/sc_man_scanner.h"
yy364:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy365;
	if(yych != 'n') goto yy176;
yy365:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy366;
	if(yych != 'd') goto yy176;
yy366:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy367;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy367;
			if(yych <= 'z') goto yy175;
		}
	}
yy367:
#line 97 "src/sc_man_scanner.re"
	{ RET(TK_Sound); }
#line 2506 "src/sc_man_scanner.h"
yy368:
	yych = *++YYCURSOR;
	if(yych == 'G') goto yy369;
	if(yych != 'g') goto yy176;
yy369:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy370;
	if(yych != 'u') goto yy176;
yy370:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy371;
	if(yych != 'l') goto yy176;
yy371:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy372;
	if(yych != 'a') goto yy176;
yy372:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy373;
	if(yych != 'r') goto yy176;
yy373:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy374;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy374;
			if(yych <= 'z') goto yy175;
		}
	}
yy374:
#line 129 "src/sc_man_scanner.re"
	{ RET(TK_Singular); }
#line 2544 "src/sc_man_scanner.h"
yy375:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy376;
	if(yych != 'r') goto yy176;
yy376:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy377;
	if(yych != 't') goto yy176;
yy377:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy378;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy378;
			if(yych <= 'z') goto yy175;
		}
	}
yy378:
#line 84 "src/sc_man_scanner.re"
	{ RET(TK_Short); }
#line 2570 "src/sc_man_scanner.h"
yy379:
	yych = *++YYCURSOR;
	if(yych == 'F') goto yy380;
	if(yych != 'f') goto yy176;
yy380:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy381;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy381;
			if(yych <= 'z') goto yy175;
		}
	}
yy381:
#line 138 "src/sc_man_scanner.re"
	{ RET(TK_Self); }
#line 2592 "src/sc_man_scanner.h"
yy382:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy383;
	if(yych != 't') goto yy176;
yy383:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy384;
	if(yych != 'e') goto yy176;
yy384:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy385;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy385;
			if(yych <= 'z') goto yy175;
		}
	}
yy385:
#line 83 "src/sc_man_scanner.re"
	{ RET(TK_SByte); }
#line 2618 "src/sc_man_scanner.h"
yy386:
	yych = *++YYCURSOR;
	if(yych <= 'T') {
		if(yych == 'F') goto yy388;
		if(yych <= 'S') goto yy176;
	} else {
		if(yych <= 'f') {
			if(yych <= 'e') goto yy176;
			goto yy388;
		} else {
			if(yych != 't') goto yy176;
		}
	}
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy390;
	if(yych == 'u') goto yy390;
	goto yy176;
yy388:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy389;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy389;
			if(yych <= 'z') goto yy175;
		}
	}
yy389:
#line 114 "src/sc_man_scanner.re"
	{ RET(TK_Ref); }
#line 2653 "src/sc_man_scanner.h"
yy390:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy391;
	if(yych != 'r') goto yy176;
yy391:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy392;
	if(yych != 'n') goto yy176;
yy392:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy393;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy393;
			if(yych <= 'z') goto yy175;
		}
	}
yy393:
#line 70 "src/sc_man_scanner.re"
	{ RET(TK_Return); }
#line 2679 "src/sc_man_scanner.h"
yy394:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy395;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy395;
			if(yych <= 'z') goto yy175;
		}
	}
yy395:
#line 69 "src/sc_man_scanner.re"
	{ RET(TK_If); }
#line 2697 "src/sc_man_scanner.h"
yy396:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy417;
	if(yych == 'n') goto yy417;
	goto yy176;
yy397:
	yych = *++YYCURSOR;
	if(yych <= 'T') {
		if(yych <= 'R') goto yy176;
		if(yych <= 'S') goto yy408;
		goto yy406;
	} else {
		if(yych <= 'r') goto yy176;
		if(yych <= 's') goto yy408;
		if(yych <= 't') goto yy406;
		goto yy176;
	}
yy398:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy399;
	if(yych != 'e') goto yy176;
yy399:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy400;
	if(yych != 'r') goto yy176;
yy400:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy401;
	if(yych != 'a') goto yy176;
yy401:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy402;
	if(yych != 't') goto yy176;
yy402:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy403;
	if(yych != 'o') goto yy176;
yy403:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy404;
	if(yych != 'r') goto yy176;
yy404:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy405;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy405;
			if(yych <= 'z') goto yy175;
		}
	}
yy405:
#line 132 "src/sc_man_scanner.re"
	{ RET(TK_Iterator); }
#line 2756 "src/sc_man_scanner.h"
yy406:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy407;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy407;
			if(yych <= 'z') goto yy175;
		}
	}
yy407:
#line 86 "src/sc_man_scanner.re"
	{ RET(TK_Int); }
#line 2774 "src/sc_man_scanner.h"
yy408:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy409;
	if(yych != 't') goto yy176;
yy409:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy410;
	if(yych != 'a') goto yy176;
yy410:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy411;
	if(yych != 'n') goto yy176;
yy411:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy412;
	if(yych != 'c') goto yy176;
yy412:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy413;
	if(yych != 'e') goto yy176;
yy413:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy414;
	if(yych != 'o') goto yy176;
yy414:
	yych = *++YYCURSOR;
	if(yych == 'F') goto yy415;
	if(yych != 'f') goto yy176;
yy415:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy416;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy416;
			if(yych <= 'z') goto yy175;
		}
	}
yy416:
#line 108 "src/sc_man_scanner.re"
	{ RET(TK_InstanceOf); }
#line 2820 "src/sc_man_scanner.h"
yy417:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy418;
	if(yych != 'o') goto yy176;
yy418:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy419;
	if(yych != 'r') goto yy176;
yy419:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy420;
	if(yych != 'e') goto yy176;
yy420:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy421;
	if(yych != 's') goto yy176;
yy421:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy422;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy422;
			if(yych <= 'z') goto yy175;
		}
	}
yy422:
#line 126 "src/sc_man_scanner.re"
	{ RET(TK_Ignores); }
#line 2854 "src/sc_man_scanner.h"
yy423:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy428;
	if(yych == 'o') goto yy428;
	goto yy176;
yy424:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy425;
	if(yych != 't') goto yy176;
yy425:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy426;
	if(yych != 'o') goto yy176;
yy426:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy427;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy427;
			if(yych <= 'z') goto yy175;
		}
	}
yy427:
#line 68 "src/sc_man_scanner.re"
	{ RET(TK_Goto); }
#line 2885 "src/sc_man_scanner.h"
yy428:
	yych = *++YYCURSOR;
	if(yych == 'B') goto yy429;
	if(yych != 'b') goto yy176;
yy429:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy430;
	if(yych != 'a') goto yy176;
yy430:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy431;
	if(yych != 'l') goto yy176;
yy431:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy432;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy432;
			if(yych <= 'z') goto yy175;
		}
	}
yy432:
#line 137 "src/sc_man_scanner.re"
	{ RET(TK_Global); }
#line 2915 "src/sc_man_scanner.h"
yy433:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy452;
	if(yych == 'l') goto yy452;
	goto yy176;
yy434:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy448;
	if(yych == 'n') goto yy448;
	goto yy176;
yy435:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy444;
	if(yych == 'o') goto yy444;
	goto yy176;
yy436:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy437;
	if(yych != 'r') goto yy176;
yy437:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '@') {
			if(yych <= '/') goto yy438;
			if(yych <= '9') goto yy175;
		} else {
			if(yych == 'E') goto yy439;
			goto yy175;
		}
	} else {
		if(yych <= '`') {
			if(yych == '_') goto yy175;
		} else {
			if(yych == 'e') goto yy439;
			if(yych <= 'z') goto yy175;
		}
	}
yy438:
#line 67 "src/sc_man_scanner.re"
	{ RET(TK_For); }
#line 2956 "src/sc_man_scanner.h"
yy439:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy440;
	if(yych != 'a') goto yy176;
yy440:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy441;
	if(yych != 'c') goto yy176;
yy441:
	yych = *++YYCURSOR;
	if(yych == 'H') goto yy442;
	if(yych != 'h') goto yy176;
yy442:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy443;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy443;
			if(yych <= 'z') goto yy175;
		}
	}
yy443:
#line 103 "src/sc_man_scanner.re"
	{ RET(TK_ForEach); }
#line 2986 "src/sc_man_scanner.h"
yy444:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy445;
	if(yych != 'a') goto yy176;
yy445:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy446;
	if(yych != 't') goto yy176;
yy446:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy447;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy447;
			if(yych <= 'z') goto yy175;
		}
	}
yy447:
#line 79 "src/sc_man_scanner.re"
	{ RET(TK_Float); }
#line 3012 "src/sc_man_scanner.h"
yy448:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy449;
	if(yych != 'a') goto yy176;
yy449:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy450;
	if(yych != 'l') goto yy176;
yy450:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy451;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy451;
			if(yych <= 'z') goto yy175;
		}
	}
yy451:
#line 118 "src/sc_man_scanner.re"
	{ RET(TK_Final); }
#line 3038 "src/sc_man_scanner.h"
yy452:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy453;
	if(yych != 's') goto yy176;
yy453:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy454;
	if(yych != 'e') goto yy176;
yy454:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy455;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy455;
			if(yych <= 'z') goto yy175;
		}
	}
yy455:
#line 105 "src/sc_man_scanner.re"
	{ RET(TK_False); }
#line 3064 "src/sc_man_scanner.h"
yy456:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy488;
	if(yych == 's') goto yy488;
	goto yy176;
yy457:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy485;
	if(yych == 'u') goto yy485;
	goto yy176;
yy458:
	yych = *++YYCURSOR;
	if(yych <= 'E') {
		if(yych == 'A') goto yy475;
		if(yych <= 'D') goto yy176;
		goto yy474;
	} else {
		if(yych <= 'a') {
			if(yych <= '`') goto yy176;
			goto yy475;
		} else {
			if(yych == 'e') goto yy474;
			goto yy176;
		}
	}
yy459:
	yych = *++YYCURSOR;
	if(yych <= 'T') {
		if(yych <= 'O') {
			if(yych != 'E') goto yy176;
		} else {
			if(yych <= 'P') goto yy462;
			if(yych <= 'S') goto yy176;
			goto yy461;
		}
	} else {
		if(yych <= 'o') {
			if(yych != 'e') goto yy176;
		} else {
			if(yych <= 'p') goto yy462;
			if(yych == 't') goto yy461;
			goto yy176;
		}
	}
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy472;
	if(yych == 'c') goto yy472;
	goto yy176;
yy461:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy467;
	if(yych == 'e') goto yy467;
	goto yy176;
yy462:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy463;
	if(yych != 'o') goto yy176;
yy463:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy464;
	if(yych != 'r') goto yy176;
yy464:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy465;
	if(yych != 't') goto yy176;
yy465:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy466;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy466;
			if(yych <= 'z') goto yy175;
		}
	}
yy466:
#line 134 "src/sc_man_scanner.re"
	{ RET(TK_Export); }
#line 3147 "src/sc_man_scanner.h"
yy467:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy468;
	if(yych != 'n') goto yy176;
yy468:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy469;
	if(yych != 'd') goto yy176;
yy469:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy470;
	if(yych != 's') goto yy176;
yy470:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy471;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy471;
			if(yych <= 'z') goto yy175;
		}
	}
yy471:
#line 120 "src/sc_man_scanner.re"
	{ RET(TK_Extends); }
#line 3177 "src/sc_man_scanner.h"
yy472:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy473;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy473;
			if(yych <= 'z') goto yy175;
		}
	}
yy473:
#line 110 "src/sc_man_scanner.re"
	{ RET(TK_Exec); }
#line 3195 "src/sc_man_scanner.h"
yy474:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy482;
	if(yych == 'n') goto yy482;
	goto yy176;
yy475:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy476;
	if(yych != 'l') goto yy176;
yy476:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '@') {
			if(yych <= '/') goto yy477;
			if(yych <= '9') goto yy175;
		} else {
			if(yych == 'N') goto yy478;
			goto yy175;
		}
	} else {
		if(yych <= '`') {
			if(yych == '_') goto yy175;
		} else {
			if(yych == 'n') goto yy478;
			if(yych <= 'z') goto yy175;
		}
	}
yy477:
#line 142 "src/sc_man_scanner.re"
	{ RET(TK_Eval); }
#line 3226 "src/sc_man_scanner.h"
yy478:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy479;
	if(yych != 'o') goto yy176;
yy479:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy480;
	if(yych != 't') goto yy176;
yy480:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy481;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy481;
			if(yych <= 'z') goto yy175;
		}
	}
yy481:
#line 143 "src/sc_man_scanner.re"
	{ RET(TK_EvalNot); }
#line 3252 "src/sc_man_scanner.h"
yy482:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy483;
	if(yych != 't') goto yy176;
yy483:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy484;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy484;
			if(yych <= 'z') goto yy175;
		}
	}
yy484:
#line 115 "src/sc_man_scanner.re"
	{ RET(TK_Event); }
#line 3274 "src/sc_man_scanner.h"
yy485:
	yych = *++YYCURSOR;
	if(yych == 'M') goto yy486;
	if(yych != 'm') goto yy176;
yy486:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy487;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy487;
			if(yych <= 'z') goto yy175;
		}
	}
yy487:
#line 94 "src/sc_man_scanner.re"
	{ RET(TK_Enum); }
#line 3296 "src/sc_man_scanner.h"
yy488:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy489;
	if(yych != 'e') goto yy176;
yy489:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy490;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy490;
			if(yych <= 'z') goto yy175;
		}
	}
yy490:
#line 66 "src/sc_man_scanner.re"
	{ RET(TK_Else); }
#line 3318 "src/sc_man_scanner.h"
yy491:
	yych = *++YYCURSOR;
	if(yych == 'F') goto yy501;
	if(yych == 'f') goto yy501;
	goto yy176;
yy492:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '@') {
			if(yych <= '/') goto yy493;
			if(yych <= '9') goto yy175;
		} else {
			if(yych <= 'S') goto yy175;
			if(yych <= 'T') goto yy495;
			if(yych <= 'U') goto yy494;
			goto yy175;
		}
	} else {
		if(yych <= 's') {
			if(yych == '_') goto yy175;
			if(yych >= 'a') goto yy175;
		} else {
			if(yych <= 't') goto yy495;
			if(yych <= 'u') goto yy494;
			if(yych <= 'z') goto yy175;
		}
	}
yy493:
#line 65 "src/sc_man_scanner.re"
	{ RET(TK_Do); }
#line 3349 "src/sc_man_scanner.h"
yy494:
	yych = *++YYCURSOR;
	if(yych == 'B') goto yy497;
	if(yych == 'b') goto yy497;
	goto yy176;
yy495:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy496;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy496;
			if(yych <= 'z') goto yy175;
		}
	}
yy496:
#line 124 "src/sc_man_scanner.re"
	{ RET(TK_Dot); }
#line 3372 "src/sc_man_scanner.h"
yy497:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy498;
	if(yych != 'l') goto yy176;
yy498:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy499;
	if(yych != 'e') goto yy176;
yy499:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy500;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy500;
			if(yych <= 'z') goto yy175;
		}
	}
yy500:
#line 80 "src/sc_man_scanner.re"
	{ RET(TK_Double); }
#line 3398 "src/sc_man_scanner.h"
yy501:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy502;
	if(yych != 'a') goto yy176;
yy502:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy503;
	if(yych != 'u') goto yy176;
yy503:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy504;
	if(yych != 'l') goto yy176;
yy504:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy505;
	if(yych != 't') goto yy176;
yy505:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '@') {
			if(yych <= '/') goto yy506;
			if(yych <= '9') goto yy175;
		} else {
			if(yych == 'P') goto yy507;
			goto yy175;
		}
	} else {
		if(yych <= '`') {
			if(yych == '_') goto yy175;
		} else {
			if(yych == 'p') goto yy507;
			if(yych <= 'z') goto yy175;
		}
	}
yy506:
#line 64 "src/sc_man_scanner.re"
	{ RET(TK_Default); }
#line 3436 "src/sc_man_scanner.h"
yy507:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy508;
	if(yych != 'r') goto yy176;
yy508:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy509;
	if(yych != 'o') goto yy176;
yy509:
	yych = *++YYCURSOR;
	if(yych == 'P') goto yy510;
	if(yych != 'p') goto yy176;
yy510:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy511;
	if(yych != 'e') goto yy176;
yy511:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy512;
	if(yych != 'r') goto yy176;
yy512:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy513;
	if(yych != 't') goto yy176;
yy513:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy514;
	if(yych != 'i') goto yy176;
yy514:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy515;
	if(yych != 'e') goto yy176;
yy515:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy516;
	if(yych != 's') goto yy176;
yy516:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy517;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy517;
			if(yych <= 'z') goto yy175;
		}
	}
yy517:
#line 111 "src/sc_man_scanner.re"
	{ RET(TK_DefaultProperties); }
#line 3490 "src/sc_man_scanner.h"
yy518:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy557;
	if(yych == 's') goto yy557;
	goto yy176;
yy519:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy554;
	if(yych == 'a') goto yy554;
	goto yy176;
yy520:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy550;
	if(yych == 'a') goto yy550;
	goto yy176;
yy521:
	yych = *++YYCURSOR;
	if(yych <= 'N') {
		if(yych <= 'K') {
			if(yych == 'E') goto yy529;
			goto yy176;
		} else {
			if(yych <= 'L') goto yy528;
			if(yych <= 'M') goto yy176;
			goto yy527;
		}
	} else {
		if(yych <= 'k') {
			if(yych == 'e') goto yy529;
			goto yy176;
		} else {
			if(yych <= 'l') goto yy528;
			if(yych == 'n') goto yy527;
			goto yy176;
		}
	}
yy522:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy523;
	if(yych != 'o') goto yy176;
yy523:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy524;
	if(yych != 's') goto yy176;
yy524:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy525;
	if(yych != 's') goto yy176;
yy525:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy526;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy526;
			if(yych <= 'z') goto yy175;
		}
	}
yy526:
#line 125 "src/sc_man_scanner.re"
	{ RET(TK_Cross); }
#line 3556 "src/sc_man_scanner.h"
yy527:
	yych = *++YYCURSOR;
	if(yych <= 'T') {
		if(yych <= 'F') {
			if(yych <= 'E') goto yy176;
			goto yy537;
		} else {
			if(yych <= 'R') goto yy176;
			if(yych <= 'S') goto yy538;
			goto yy539;
		}
	} else {
		if(yych <= 'r') {
			if(yych == 'f') goto yy537;
			goto yy176;
		} else {
			if(yych <= 's') goto yy538;
			if(yych <= 't') goto yy539;
			goto yy176;
		}
	}
yy528:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy534;
	if(yych == 'o') goto yy534;
	goto yy176;
yy529:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy530;
	if(yych != 'r') goto yy176;
yy530:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy531;
	if(yych != 'c') goto yy176;
yy531:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy532;
	if(yych != 'e') goto yy176;
yy532:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy533;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy533;
			if(yych <= 'z') goto yy175;
		}
	}
yy533:
#line 131 "src/sc_man_scanner.re"
	{ RET(TK_Coerce); }
#line 3612 "src/sc_man_scanner.h"
yy534:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy535;
	if(yych != 'r') goto yy176;
yy535:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy536;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy536;
			if(yych <= 'z') goto yy175;
		}
	}
yy536:
#line 99 "src/sc_man_scanner.re"
	{ RET(TK_Color); }
#line 3634 "src/sc_man_scanner.h"
yy537:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy547;
	if(yych == 'i') goto yy547;
	goto yy176;
yy538:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy545;
	if(yych == 't') goto yy545;
	goto yy176;
yy539:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy540;
	if(yych != 'i') goto yy176;
yy540:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy541;
	if(yych != 'n') goto yy176;
yy541:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy542;
	if(yych != 'u') goto yy176;
yy542:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy543;
	if(yych != 'e') goto yy176;
yy543:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy544;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy544;
			if(yych <= 'z') goto yy175;
		}
	}
yy544:
#line 63 "src/sc_man_scanner.re"
	{ RET(TK_Continue); }
#line 3678 "src/sc_man_scanner.h"
yy545:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy546;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy546;
			if(yych <= 'z') goto yy175;
		}
	}
yy546:
#line 62 "src/sc_man_scanner.re"
	{ RET(TK_Const); }
#line 3696 "src/sc_man_scanner.h"
yy547:
	yych = *++YYCURSOR;
	if(yych == 'G') goto yy548;
	if(yych != 'g') goto yy176;
yy548:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy549;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy549;
			if(yych <= 'z') goto yy175;
		}
	}
yy549:
#line 130 "src/sc_man_scanner.re"
	{ RET(TK_Config); }
#line 3718 "src/sc_man_scanner.h"
yy550:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy551;
	if(yych != 's') goto yy176;
yy551:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy552;
	if(yych != 's') goto yy176;
yy552:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy553;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy553;
			if(yych <= 'z') goto yy175;
		}
	}
yy553:
#line 92 "src/sc_man_scanner.re"
	{ RET(TK_Class); }
#line 3744 "src/sc_man_scanner.h"
yy554:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy555;
	if(yych != 'r') goto yy176;
yy555:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy556;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy556;
			if(yych <= 'z') goto yy175;
		}
	}
yy556:
#line 81 "src/sc_man_scanner.re"
	{ RET(TK_Char); }
#line 3766 "src/sc_man_scanner.h"
yy557:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy558;
	if(yych != 'e') goto yy176;
yy558:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy559;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy559;
			if(yych <= 'z') goto yy175;
		}
	}
yy559:
#line 61 "src/sc_man_scanner.re"
	{ RET(TK_Case); }
#line 3788 "src/sc_man_scanner.h"
yy560:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy570;
	if(yych == 'o') goto yy570;
	goto yy176;
yy561:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy566;
	if(yych == 'e') goto yy566;
	goto yy176;
yy562:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy563;
	if(yych != 't') goto yy176;
yy563:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy564;
	if(yych != 'e') goto yy176;
yy564:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy565;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy565;
			if(yych <= 'z') goto yy175;
		}
	}
yy565:
#line 82 "src/sc_man_scanner.re"
	{ RET(TK_Byte); }
#line 3824 "src/sc_man_scanner.h"
yy566:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy567;
	if(yych != 'a') goto yy176;
yy567:
	yych = *++YYCURSOR;
	if(yych == 'K') goto yy568;
	if(yych != 'k') goto yy176;
yy568:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy569;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy569;
			if(yych <= 'z') goto yy175;
		}
	}
yy569:
#line 60 "src/sc_man_scanner.re"
	{ RET(TK_Break); }
#line 3850 "src/sc_man_scanner.h"
yy570:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy571;
	if(yych != 'l') goto yy176;
yy571:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z') {
		if(yych <= '/') goto yy572;
		if(yych <= '9') goto yy175;
		if(yych >= 'A') goto yy175;
	} else {
		if(yych <= '_') {
			if(yych >= '_') goto yy175;
		} else {
			if(yych <= '`') goto yy572;
			if(yych <= 'z') goto yy175;
		}
	}
yy572:
#line 78 "src/sc_man_scanner.re"
	{ RET(TK_Bool); }
#line 3872 "src/sc_man_scanner.h"
yy573:
	++YYCURSOR;
#line 167 "src/sc_man_scanner.re"
	{ RET(TK_DivEq); }
#line 3877 "src/sc_man_scanner.h"
yy575:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x0A) goto yy579;
	goto yy575;
yy577:
	++YYCURSOR;
#line 56 "src/sc_man_scanner.re"
	{ goto comment; }
#line 3888 "src/sc_man_scanner.h"
yy579:
	++YYCURSOR;
#line 57 "src/sc_man_scanner.re"
	{ goto newline; }
#line 3893 "src/sc_man_scanner.h"
}
#line 215 "src/sc_man_scanner.re"

	}
	if (!CMode)	// The classic Hexen scanner.
	{
	
#line 3901 "src/sc_man_scanner.h"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= '/') {
		if(yych <= ' ') {
			if(yych == 0x0A) goto yy589;
			goto yy587;
		} else {
			if(yych == '"') goto yy591;
			if(yych <= '.') goto yy595;
			goto yy584;
		}
	} else {
		if(yych <= '<') {
			if(yych == ';') goto yy586;
			goto yy595;
		} else {
			if(yych <= '=') goto yy593;
			if(yych <= 'z') goto yy595;
			if(yych <= '}') goto yy593;
			goto yy595;
		}
	}
yy583:
#line 230 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 3930 "src/sc_man_scanner.h"
yy584:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '/') {
		if(yych <= '"') {
			if(yych == '!') goto yy600;
		} else {
			if(yych == '*') goto yy608;
			if(yych <= '.') goto yy600;
			goto yy604;
		}
	} else {
		if(yych <= '<') {
			if(yych != ';') goto yy600;
		} else {
			if(yych <= '=') goto yy585;
			if(yych <= 'z') goto yy600;
			if(yych >= '~') goto yy600;
		}
	}
yy585:
#line 232 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 3954 "src/sc_man_scanner.h"
yy586:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy605;
yy587:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy603;
yy588:
#line 223 "src/sc_man_scanner.re"
	{ goto std1; }
#line 3966 "src/sc_man_scanner.h"
yy589:
	++YYCURSOR;
#line 224 "src/sc_man_scanner.re"
	{ goto newline; }
#line 3971 "src/sc_man_scanner.h"
yy591:
	++YYCURSOR;
#line 225 "src/sc_man_scanner.re"
	{ goto string; }
#line 3976 "src/sc_man_scanner.h"
yy593:
	++YYCURSOR;
#line 227 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 3981 "src/sc_man_scanner.h"
yy595:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy599;
yy596:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '/') {
		if(yych <= '"') {
			if(yych == '!') goto yy600;
		} else {
			if(yych == '*') goto yy597;
			if(yych <= '.') goto yy600;
		}
	} else {
		if(yych <= '<') {
			if(yych != ';') goto yy600;
		} else {
			if(yych <= '=') goto yy597;
			if(yych <= 'z') goto yy600;
			if(yych >= '~') goto yy600;
		}
	}
yy597:
	YYCURSOR = YYMARKER;
	if(yyaccept <= 0) {
		goto yy585;
	} else {
		goto yy583;
	}
yy598:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy599:
	if(yych <= ':') {
		if(yych <= '"') {
			if(yych == '!') goto yy598;
			goto yy583;
		} else {
			if(yych == '/') goto yy596;
			goto yy598;
		}
	} else {
		if(yych <= '=') {
			if(yych == '<') goto yy598;
			goto yy583;
		} else {
			if(yych <= 'z') goto yy598;
			if(yych <= '}') goto yy583;
			goto yy598;
		}
	}
yy600:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= ':') {
		if(yych <= '"') {
			if(yych == '!') goto yy600;
			goto yy583;
		} else {
			if(yych == '/') goto yy596;
			goto yy600;
		}
	} else {
		if(yych <= '=') {
			if(yych == '<') goto yy600;
			goto yy583;
		} else {
			if(yych <= 'z') goto yy600;
			if(yych <= '}') goto yy583;
			goto yy600;
		}
	}
yy602:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy603:
	if(yych == 0x0A) goto yy588;
	if(yych <= ' ') goto yy602;
	goto yy588;
yy604:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy605:
	if(yych != 0x0A) goto yy604;
	++YYCURSOR;
#line 221 "src/sc_man_scanner.re"
	{ goto newline; }
#line 4077 "src/sc_man_scanner.h"
yy608:
	++YYCURSOR;
#line 220 "src/sc_man_scanner.re"
	{ goto comment; }
#line 4082 "src/sc_man_scanner.h"
}
#line 233 "src/sc_man_scanner.re"

	}
	else		// A modified Hexen scanner for DECORATE.
	{
	
#line 4090 "src/sc_man_scanner.h"
{
	YYCTYPE yych;
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= ':') {
		if(yych <= '&') {
			if(yych <= ' ') {
				if(yych == 0x0A) goto yy616;
				goto yy614;
			} else {
				if(yych == '"') goto yy618;
				if(yych <= '%') goto yy631;
				goto yy626;
			}
		} else {
			if(yych <= '-') {
				if(yych <= '\'') goto yy632;
				if(yych <= ',') goto yy631;
				goto yy620;
			} else {
				if(yych <= '.') goto yy624;
				if(yych <= '/') goto yy612;
				if(yych <= '9') goto yy622;
				goto yy625;
			}
		}
	} else {
		if(yych <= '^') {
			if(yych <= '=') {
				if(yych <= ';') goto yy631;
				if(yych <= '<') goto yy629;
				goto yy627;
			} else {
				if(yych <= '>') goto yy630;
				if(yych <= '@') goto yy631;
				if(yych <= 'Z') goto yy632;
				goto yy631;
			}
		} else {
			if(yych <= 'z') {
				if(yych == '`') goto yy631;
				goto yy632;
			} else {
				if(yych == '|') goto yy628;
				if(yych <= '~') goto yy631;
				goto yy632;
			}
		}
	}
yy612:
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '*') goto yy658;
	if(yych == '/') goto yy656;
yy613:
#line 253 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4147 "src/sc_man_scanner.h"
yy614:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy655;
yy615:
#line 241 "src/sc_man_scanner.re"
	{ goto std1; }
#line 4155 "src/sc_man_scanner.h"
yy616:
	++YYCURSOR;
#line 242 "src/sc_man_scanner.re"
	{ goto newline; }
#line 4160 "src/sc_man_scanner.h"
yy618:
	++YYCURSOR;
#line 243 "src/sc_man_scanner.re"
	{ goto string; }
#line 4165 "src/sc_man_scanner.h"
yy620:
	++YYCURSOR;
#line 245 "src/sc_man_scanner.re"
	{ goto negative_check; }
#line 4170 "src/sc_man_scanner.h"
yy622:
	++YYCURSOR;
	if((yych = *YYCURSOR) == '.') goto yy652;
	if(yych <= '/') goto yy634;
	if(yych <= '9') goto yy650;
	goto yy634;
yy623:
#line 254 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4180 "src/sc_man_scanner.h"
yy624:
	yych = *++YYCURSOR;
	if(yych <= '/') goto yy613;
	if(yych <= '9') goto yy647;
	goto yy613;
yy625:
	yych = *++YYCURSOR;
	if(yych == ':') goto yy645;
	goto yy613;
yy626:
	yych = *++YYCURSOR;
	if(yych == '&') goto yy643;
	goto yy613;
yy627:
	yych = *++YYCURSOR;
	if(yych == '=') goto yy641;
	goto yy613;
yy628:
	yych = *++YYCURSOR;
	if(yych == '|') goto yy639;
	goto yy613;
yy629:
	yych = *++YYCURSOR;
	if(yych == '<') goto yy637;
	goto yy613;
yy630:
	yych = *++YYCURSOR;
	if(yych == '>') goto yy635;
	goto yy613;
yy631:
	yych = *++YYCURSOR;
	goto yy613;
yy632:
	yych = *++YYCURSOR;
	goto yy634;
yy633:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy634:
	if(yych <= 'Z') {
		if(yych <= '/') {
			if(yych == '\'') goto yy633;
			goto yy623;
		} else {
			if(yych <= '9') goto yy633;
			if(yych <= '@') goto yy623;
			goto yy633;
		}
	} else {
		if(yych <= '`') {
			if(yych == '_') goto yy633;
			goto yy623;
		} else {
			if(yych <= 'z') goto yy633;
			if(yych <= '~') goto yy623;
			goto yy633;
		}
	}
yy635:
	++YYCURSOR;
#line 252 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4244 "src/sc_man_scanner.h"
yy637:
	++YYCURSOR;
#line 251 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4249 "src/sc_man_scanner.h"
yy639:
	++YYCURSOR;
#line 250 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4254 "src/sc_man_scanner.h"
yy641:
	++YYCURSOR;
#line 249 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4259 "src/sc_man_scanner.h"
yy643:
	++YYCURSOR;
#line 248 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4264 "src/sc_man_scanner.h"
yy645:
	++YYCURSOR;
#line 247 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4269 "src/sc_man_scanner.h"
yy647:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '/') goto yy649;
	if(yych <= '9') goto yy647;
yy649:
#line 246 "src/sc_man_scanner.re"
	{ goto normal_token; }
#line 4279 "src/sc_man_scanner.h"
yy650:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '@') {
		if(yych <= '-') {
			if(yych == '\'') goto yy633;
			goto yy623;
		} else {
			if(yych <= '.') goto yy652;
			if(yych <= '/') goto yy623;
			if(yych <= '9') goto yy650;
			goto yy623;
		}
	} else {
		if(yych <= '_') {
			if(yych <= 'Z') goto yy633;
			if(yych <= '^') goto yy623;
			goto yy633;
		} else {
			if(yych <= '`') goto yy623;
			if(yych <= 'z') goto yy633;
			if(yych <= '~') goto yy623;
			goto yy633;
		}
	}
yy652:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '/') goto yy649;
	if(yych <= '9') goto yy652;
	goto yy649;
yy654:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy655:
	if(yych == 0x0A) goto yy615;
	if(yych <= ' ') goto yy654;
	goto yy615;
yy656:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych == 0x0A) goto yy660;
	goto yy656;
yy658:
	++YYCURSOR;
#line 238 "src/sc_man_scanner.re"
	{ goto comment; }
#line 4331 "src/sc_man_scanner.h"
yy660:
	++YYCURSOR;
#line 239 "src/sc_man_scanner.re"
	{ goto newline; }
#line 4336 "src/sc_man_scanner.h"
}
#line 257 "src/sc_man_scanner.re"

	}

negative_check:
	// re2c doesn't have enough state to handle '-' as the start of a negative number
	// and as its own token, so help it out a little.
	sc_TokenType = '-';
	if (YYCURSOR >= YYLIMIT)
	{
		goto normal_token;
	}
	if (*YYCURSOR >= '0' && *YYCURSOR <= '9')
	{
		goto std2;
	}
	if (*YYCURSOR != '.' || YYCURSOR+1 >= YYLIMIT)
	{
		goto normal_token;
	}
	if (*(YYCURSOR+1) >= '0' && *YYCURSOR <= '9')
	{
		goto std2;
	}
	goto normal_token;

comment:

#line 4366 "src/sc_man_scanner.h"
{
	YYCTYPE yych;
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych == 0x0A) goto yy666;
	if(yych != '*') goto yy668;
	++YYCURSOR;
	if((yych = *YYCURSOR) == '/') goto yy669;
yy665:
#line 306 "src/sc_man_scanner.re"
	{ goto comment; }
#line 4378 "src/sc_man_scanner.h"
yy666:
	++YYCURSOR;
#line 295 "src/sc_man_scanner.re"
	{
			if (YYCURSOR >= YYLIMIT)
			{
				ScriptPtr = ScriptEndPtr;
				return_val = false;
				goto end;
			}
			sc_Line++;
			sc_Crossed = true;
			goto comment;
		}
#line 4393 "src/sc_man_scanner.h"
yy668:
	yych = *++YYCURSOR;
	goto yy665;
yy669:
	++YYCURSOR;
#line 285 "src/sc_man_scanner.re"
	{
			if (YYCURSOR >= YYLIMIT)
			{
				ScriptPtr = ScriptEndPtr;
				return_val = false;
				goto end;
			}
			goto std1;
		}
#line 4409 "src/sc_man_scanner.h"
}
#line 307 "src/sc_man_scanner.re"


newline:
	if (YYCURSOR >= YYLIMIT)
	{
		ScriptPtr = ScriptEndPtr;
		return_val = false;
		goto end;
	}
	sc_Line++;
	sc_Crossed = true;
	goto std1;

normal_token:
	ScriptPtr = (YYCURSOR >= YYLIMIT) ? ScriptEndPtr : cursor;
	sc_StringLen = MIN (ScriptPtr - tok, MAX_STRING_SIZE-1);
	if (tokens && (sc_TokenType == TK_StringConst || sc_TokenType == TK_NameConst))
	{
		sc_StringLen -= 2;
		memcpy (sc_String, tok+1, sc_StringLen);
	}
	else
	{
		memcpy (sc_String, tok, sc_StringLen);
	}
	sc_String[sc_StringLen] = '\0';
	return_val = true;
	goto end;

string:
	if (YYLIMIT != ScriptEndPtr)
	{
		ScriptPtr = ScriptEndPtr;
		return_val = false;
		goto end;
	}
	ScriptPtr = cursor;
	for (sc_StringLen = 0; cursor < YYLIMIT; ++cursor)
	{
		if (Escape && *cursor == '\\' && *(cursor + 1) == '"')
		{
			cursor++;
		}
		else if (*cursor == '\r' && *(cursor + 1) == '\n')
		{
			cursor++;	// convert CR-LF to simply LF
		}
		else if (*cursor == '"')
		{
			break;
		}
		if (*cursor == '\n')
		{
			if (CMode)
			{
				if (!Escape || sc_StringLen == 0 || sc_String[sc_StringLen - 1] != '\\')
				{
					SC_ScriptError ("Unterminated string constant");
				}
				else
				{
					sc_StringLen--;		// overwrite the \ character with \n
				}
			}
			sc_Line++;
			sc_Crossed = true;
		}
		if (sc_StringLen < MAX_STRING_SIZE-1)
		{
			sc_String[sc_StringLen++] = *cursor;
		}
	}
	ScriptPtr = cursor + 1;
	sc_String[sc_StringLen] = '\0';
	return_val = true;
end:
